name: Install Rust tool chain and protoc

inputs:
  target:
    description: "Specified target for rust toolchain, ex. x86_64-apple-darwin"
    type: string
    required: false
    default: "x86_64-unknown-linux-gnu"
    options:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
  github-token:
    description: "GitHub token"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      with:
        targets: ${{ inputs.target }}

    - name: Install protoc (protobuf)
      uses: arduino/setup-protoc@f4d5893b897028ff5739576ea0409746887fa536 # v3
      with:
        version: "25.1"
        repo-token: ${{ inputs.github-token }}
